apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams-recording-bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teams-recording-bot
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/teams-recording-bot
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
